/*
* This Java source file was generated by the Gradle 'init' task.
*/

package assignmentone;

import java.util.Scanner;

/**
 * This is the main class for the assignment.
 */
public class App {
  private Scanner input;

  private App(Scanner scannerInput) {
    this.input = scannerInput;
  }

  /**
   * Solution to first task.
   */
  public void helloThere() {
    System.out.print("Name, please: ");
    String name = input.nextLine();
    // using the HelloThere class.
    HelloThere helloThere = new HelloThere();
    System.out.println(helloThere.hello(name));
  }

  /**
   * Solution for the second task.
   */
  public void seconds() {
    System.out.print("Enter hours, minutes and seconds: ");
    int hours = input.nextInt();
    int minutes = input.nextInt();
    int seconds = input.nextInt();
    Time toTime = new Time();
    System.out.println(toTime.toSeconds(hours, minutes, seconds));
  }

  /**
   * Solution for the third task.
   */
  public void imInaBand() {
    Album album = new Album("Wish you were here ", 1975, "Pink Floyd");
    System.out.println(album.getName() + "was released in "
        + album.getYear() + " by " + album.getArtist());
  }

  /**
   * Solution for the fourth task.
   */
  public void bestAlbumsEver() {
    AlbumGenerator newAlbum = new AlbumGenerator();
    Album[] albums = newAlbum.generateAlbums();

    for (Album album : albums) {
      if (album != null) {
        System.out.println(album.getName() + "was released in "
            + album.getYear() + " by " + album.getArtist());
      }
    }
  }

  /**
   * Solution for the fifth task.
   */
  public void workingWithArrays() {
    int[] numbers = { 5, 2, 6, 4, 1, 3, 7, 9, 8 };
    // average of numbers in array
    ArrayAlgorithms algorithms = new ArrayAlgorithms();
    System.out.println("average is: " + algorithms.average(numbers));

    // largest value in the array
    ArrayAlgorithms algorithms2 = new ArrayAlgorithms();
    System.out.println("Largest value is: " + algorithms2.maxValue(numbers));

    // index number of smallest element
    ArrayAlgorithms algorithms3 = new ArrayAlgorithms();
    System.out.println("Index of smallest value is at position: " + algorithms3.minIndex(numbers));

    // shift element to left
    ArrayAlgorithms algorithms4 = new ArrayAlgorithms();
    int[] res = algorithms4.shift(numbers);
    System.out.println("Shifted array: ");
    for (int i : res) {
      System.out.print(i + " ");
    }

    ArrayAlgorithms algorithms5 = new ArrayAlgorithms();
    int[] result = algorithms5.shuffle(numbers);
    System.out.println("\nShuffled array: ");
    for (int i : result) {
      System.out.print(i + " ");
    }
  }

  /**
   * Starting point of the first assignment.
   *
   * @param args is not used.
   */
  public static void main(String[] args) {

    // we create a scanner object to work with
    // it is advised to create one and only one scanner for a specific stream in the
    // whole
    // application scanners should be closed when you are done and this also closes
    // the underlying stream
    Scanner consoleInput = new Scanner(System.in, "UTF-8");

    App app = new App(consoleInput);

    // Task 1
    app.helloThere();

    // // Task 2
    app.seconds();

    // // Task 3
    app.imInaBand();

    // // Task 4
    app.bestAlbumsEver();

    // // Task 5
    app.workingWithArrays();

    // If you are going for the higher grades you can uncomment the following lines
    // and implement the methods in the GradeC class.
    GradeC gradeC = new GradeC();
    gradeC.calculator(consoleInput);
    gradeC.arrays2D();
    gradeC.band();

    // Grade A tasks

    GradeA gradeA = new GradeA();
    gradeA.calculator(consoleInput);
    gradeA.arrays3D();
    // now we are exiting the application so time to close the scanner.
    consoleInput.close();
  }
}
